import ExcelJS from "exceljs";
import nodemailer from "nodemailer";

/**
 * Generates an Excel file buffer from attendance records.
 */
export async function generateAttendanceExcel(eventName: string, records: any[]): Promise<Buffer> {
  const workbook = new ExcelJS.Workbook();
  const sheet = workbook.addWorksheet("Attendance");

  // Define columns
  sheet.columns = [
    { header: "S.No", key: "sno", width: 10 },
    { header: "Name", key: "name", width: 30 },
    { header: "Roll No", key: "rollNo", width: 20 },
    { header: "Phone No", key: "phoneNo", width: 20 },
    { header: "Hostel Name", key: "hostelName", width: 20 },
    { header: "Scanned At", key: "scannedAt", width: 25 },
    { header: "Confirmed At", key: "confirmedAt", width: 25 },
  ];

  // Style header row
  sheet.getRow(1).font = { bold: true, color: { argb: "FFFFFFFF" } };
  sheet.getRow(1).fill = {
    type: "pattern",
    pattern: "solid",
    fgColor: { argb: "FF059669" }, // Emerald 600
  };

  // Helper to sanitize against Excel/CSV Formula Injection (CWE-1236)
  const sanitizeCell = (val: unknown): string => {
    if (typeof val !== "string") return val ? String(val) : "";
    const trimmed = val.trim();
    if (/^[=+\-@\t\r\n]/.test(trimmed)) {
      return "'" + trimmed;
    }
    return trimmed;
  };

  // Add data with formula injection mitigation
  records.forEach((record, index) => {
    sheet.addRow({
      sno: index + 1,
      name: sanitizeCell(record.name),
      rollNo: sanitizeCell(record.rollNo),
      phoneNo: sanitizeCell(record.phoneNo || "-"),
      hostelName: sanitizeCell(record.hostelName),
      scannedAt: new Date(record.scannedAt).toLocaleString("en-IN"),
      confirmedAt: record.confirmedAt ? new Date(record.confirmedAt).toLocaleString("en-IN") : "Pending",
    });
  });

  const buffer = await workbook.xlsx.writeBuffer();
  return Buffer.from(buffer);
}

/**
 * Sends the attendance Excel file via email.
 */
export async function sendAttendanceEmail(
  eventName: string,
  recipientEmail: string,
  excelBuffer: Buffer,
  totalAttendees: number,
  durationMinutes: number
) {
  const transporter = nodemailer.createTransport({
    service: "gmail",
    auth: {
      user: process.env.SMTP_EMAIL,
      pass: process.env.SMTP_PASSWORD,
    },
  });

  // Strip CRLF to prevent SMTP header injection
  const safeEventName = eventName.replace(/[\r\n]/g, " ").trim();
  const subject = `Attendance for ${safeEventName}`;
  const text = `Please find attached the attendance sheet for ${safeEventName}.
  
Total Attendees: ${totalAttendees}
Session Duration: ~${durationMinutes} minutes

Generated by KSAC GatePass System.`;

  await transporter.sendMail({
    from: process.env.SMTP_EMAIL,
    to: recipientEmail,
    subject,
    text,
    attachments: [
      {
        filename: `Attendance_${safeEventName.replace(/[^a-zA-Z0-9_-]/g, "_")}.xlsx`,
        content: excelBuffer,
      },
    ],
  });
}
